# Generated by Django 3.2.3 on 2021-06-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='link',
            field=models.URLField(blank=True, default=None, max_length=30, null=True, verbose_name='个人网址'),
        ),
    ]
