# Generated by Django 2.2.11 on 2020-04-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200420_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=30, verbose_name='个人网址'),
        ),
    ]
