# Generated by Django 2.2.11 on 2020-04-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': '电子邮箱已存在'}, max_length=254, unique=True, verbose_name='电子邮箱'),
        ),
    ]
