# Generated by Django 2.2.11 on 2020-05-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200429_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': '电子邮箱已存在'}, max_length=254, unique=True, verbose_name='电子邮箱'),
        ),
    ]
