repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: check-toml
    -   id: debug-statements
    -   id: name-tests-test
        args: ['--django']
    -   id: double-quote-string-fixer
    -   id: requirements-txt-fixer
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.25.0
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.17.0
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.2
    hooks:
    -   id: prettier
        types: [javascript]
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.31.0
    hooks:
    -   id: yapf
        additional_dependencies: [toml]
