version: '3'

volumes:
  static:
  esdata:

services:
  elasticsearch:
    build:
      context: .
      dockerfile: ./compose/production/elasticsearch/Dockerfile
    image: livevil_blog_elasticsearch
    container_name: livevil_blog_elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536

  redis:
    build:
      context: .
      dockerfile: compose/production/redis/Dockerfile
    image: livevil_blog_redis
    container_name: livevil_blog_redis
    working_dir: /apps
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./compose/production/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  livevil_blog:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    image: livevil_blog
    container_name: livevil_blog
    working_dir: /apps
    volumes:
      - static:/apps/static
    env_file:
      - .envs/.production
    ports:
      - "8000:8000"
    command: /start.sh
    links:
      - redis
      - elasticsearch
    depends_on:
      - elasticsearch

  nginx:
    build:
      context: .
      dockerfile: compose/production/nginx/Dockerfile
    image: livevil_blog_nginx
    container_name: livevil_blog_nginx
    volumes:
      - static:/apps/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - livevil_blog
