version: '3'

volumes:
  static:
  database:
  esdata:

services:
  elasticsearch:
    build:
      context: .
      dockerfile: ./compose/production/elasticsearch/Dockerfile
    image: liveivl_blog_elasticsearch
    container_name: liveivl_blog_elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536

  mysql:
    build:
      context: .
      dockerfile: compose/production/mysql/Dockerfile
    image: livevil_blog_mysql
    container_name: livevil_blog_mysql
    working_dir: /apps
    ports:
      - "3306:3306"
    command: /setup.sh

  redis:
    build:
      context: .
      dockerfile: compose/production/redis/Dockerfile
    image: livevil_blog_redis
    container_name: livevil_blog_redis
    working_dir: /apps
    ports:
      - "6379:6379"

  livevil_blog:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    image: livevil_blog
    container_name: livevil_blog
    working_dir: /apps
    volumes:
      - static:/apps/static
    env_file:
      - .envs/.production
    ports:
      - "8000:8000"
    command: /start.sh
    links:
      - mysql
      - redis
      - elasticsearch
    depends_on:
      - elasticsearch

  nginx:
    build:
      context: .
      dockerfile: compose/production/nginx/Dockerfile
    image: livevil_blog_nginx
    container_name: livevil_blog_nginx
    volumes:
      - static:/apps/livevil_blog/blog/static
    ports:
      - "80:80"
      - "443:443"
