# Generated by Django 3.2.3 on 2021-05-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20200705_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='is_removed',
            field=models.BooleanField(db_index=True, default=False, help_text='Check this box if the comment is inappropriate. A "This comment has been removed" message will be displayed instead.', verbose_name='is removed'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='object_pk',
            field=models.CharField(db_index=True, max_length=64, verbose_name='object ID'),
        ),
    ]
