# Generated by Django 3.2.5 on 2021-12-29 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20210515_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='created_time',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='modified_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间'),
            preserve_default=False,
        ),
    ]
