# Generated by Django 3.2.3 on 2021-05-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200707_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
