# Generated by Django 3.2.3 on 2021-05-18 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postbody'),
    ]

    operations = [
        migrations.AddField(
            model_name='postbody',
            name='main',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='正文'),
            preserve_default=False,
        ),
    ]
