# Generated by Django 3.2.3 on 2021-06-08 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postbody_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=1, unique=True, verbose_name='短网址'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postviewinfo',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='文章'),
        ),
    ]
