# Generated by Django 3.2.3 on 2021-06-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210608_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postviewinfo',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='IP'),
        ),
    ]
