# Generated by Django 3.2.3 on 2021-06-12 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_postviewinfo_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postviewinfo',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='文章'),
        ),
    ]
