# Generated by Django 2.2.11 on 2020-04-22 22:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200422_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postviewinfo',
            name='view_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='浏览时间'),
        ),
    ]
