# Generated by Django 2.2.11 on 2020-04-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200422_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='postviewinfo',
            name='ip',
            field=models.PositiveIntegerField(default=0, verbose_name='IP'),
        ),
    ]
