# Generated by Django 2.2.11 on 2020-04-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_postviewinfo_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postviewinfo',
            name='ip',
            field=models.CharField(max_length=30, verbose_name='IP'),
        ),
    ]
