# Generated by Django 2.2.11 on 2020-04-29 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200426_2248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postviewinfo',
            options={'ordering': ['-view_time'], 'verbose_name': '浏览记录', 'verbose_name_plural': '浏览记录'},
        ),
    ]
