"""
Django settings for livevil_blog project.

Generated by 'django-admin startproject' using Django 2.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'blog.apps.BlogConfig',
    'users.apps.UsersConfig',

    'crispy_forms',
    'reversion',
    'debug_toolbar',
    'pure_pagination',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # 'allauth.socialaccount.providers.weibo',
    # 'allauth.socialaccount.providers.github',
    'haystack',
    'rest_framework',

    'comments.apps.CommentsConfig',


]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'reversion.middleware.RevisionMiddleware',

]

ROOT_URLCONF = 'livevil_blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': (
            os.path.join(BASE_DIR, 'templates'),
        ),
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'livevil_blog.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

# 增加第三方登录支持
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'users.backends.EmailBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# 扩展默认User功能
AUTH_USER_MODEL = 'users.User'

# crispy-forms的模式
CRISPY_TEMPLATE_PACK = 'bootstrap3'

# django-pure-pagination设置
PAGINATION_SETTINGS = {
    'PAGE_RANGE_DISPLAYED': 4,
    'MARGIN_PAGES_DISPLAYED': 2,
    'SHOW_FIRST_PAGE_WHEN_INVALID': True,
}

# redis缓存
CACHES = {
    'default': {
        "BACKEND": 'django_redis.cache.RedisCache',
        "LOCATION": 'redis://127.0.0.1:6379/1',
        "OPTION": {
            "CLIENT_CLASS": 'django_redis.client.DefaultClient',
        }
    }
}

# allauth
SITE_ID = 1

# SOCIALACCOUNT_PROVIDERS = {
#     'github': {
#         'APP': {
#             'cilent_id': '',
#             'secret': '',
#             'key': '',
#         }
#     }
# }

ACCOUNT_AUTHENTICATION_METHOD = 'username_email'  # 可以邮箱或用户名登录
ACCOUNT_EMAIL_REQUIRED = True
LOGIN_REDIRECT_URL = '/'  # 设置登录后跳转链接
LOGOUT_REDIRECT_URL = '/'  # 设置登出后跳转链接


EMAIL_HOST = 'smtp.aliyun.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'xlivevil@aliyun.com'
EMAIL_HOST_PASSWORD = 'gs$1@OzBca'
# EMAIL_USE_TLS = True  # 是否使用TLS安全传输协议
EMAIL_USE_SSL = True
EMAIL_FROM = 'xlivevil@aliyun.com'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# TODO: 转移至local和.production

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3  # 确认邮件截至时间
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  # 注册中邮件验证方法:“强制（mandatory）”,“可选（optional）”或“否（none）”之一

ACCOUNT_EMAIL_CONFIRMATION_COOLDOWN = 180  # 邮件发送后的冷却时间(以秒为单位)

ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5  # 登录尝试失败的次数
ACCOUNT_LOGIN_ON_GET = False  # 用户登出

ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 300  # 从上次失败的登录尝试，用户被禁止尝试登录的持续时间

ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True  # 更改为True，用户一旦确认他们的电子邮件地址，就会自动登录

ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = False  # 更改或设置密码后是否自动退出

ACCOUNT_LOGIN_ON_PASSWORD_RESET = False  # 更改为True，用户将在重置密码后自动登录

ACCOUNT_SESSION_REMEMBER = None  # 控制会话的生命周期，可选项还有:False,True

ACCOUNT_SIGNUP_EMAIL_ENTER_TWICE = False  # 用户注册时是否需要输入邮箱两遍

ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = False  # 用户注册时是否需要用户输入两遍密码

ACCOUNT_USERNAME_BLACKLIST = ['admin', ]  # 用户不能使用的用户名列表

ACCOUNT_UNIQUE_EMAIL = True  # 加强电子邮件地址的唯一性

ACCOUNT_USERNAME_MIN_LENGTH = 2  # 用户名允许的最小长度的整数

SOCIALACCOUNT_AUTO_SIGNUP = True  # 使用从社会帐户提供者检索的字段(如用户名、邮件)来绕过注册表单

ACCOUNT_LOGOUT_REDIRECT_URL = "/"  # 设置退出登录后跳转链接

# APPEND_SLASH=False

# haystack

HAYSTACK_SEARCH_RESULTS_PER_PAGE = 10
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'
HAYSTACK_CUSTOM_HIGHLIGHTER = 'blog.utils.Highlighter'


SECURE_BROWSER_XSS_FILTER = True
