# Generated by Django 3.2.3 on 2021-09-01 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/file/%Y%m%d/', verbose_name='文件')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('is_public', models.BooleanField(default=True, help_text='not pubic', verbose_name='is public')),
                ('is_removed', models.BooleanField(db_index=True, default=False, help_text='removed', verbose_name='is removed')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files_files', to=settings.AUTH_USER_MODEL, verbose_name='uploader')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
