# Generated by Django 3.2.4 on 2021-09-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netdisk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='files/%Y%m%d/', verbose_name='文件'),
        ),
    ]
